name: wishlist
description: "Wishlist app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  #  talker_flutter: ^4.4.1
  #  talker_bloc_logger: ^4.4.1
  #  talker_dio_logger: ^4.4.1
  json_annotation: ^4.9.0
  auto_route: ^9.2.0
  intl: ^0.19.0
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
flutter:
  uses-material-design: true